version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      GIN_MODE: $GIN_MODE
      SECRET: $SECRET
      DOMAIN: $DOMAIN
    tty: true
    ports:
      - "$PORT:$PORT"
  batch:
    build:
      context: .
      dockerfile: Dockerfile.batch
    environment:
      DOMAIN: $DOMAIN
    tty: true
